export { default as Loginpage } from "./Loginpage"
export { default as UserNav } from "./UserNav"
export { default as UserSignup } from "./UserSignup"
export { default as CreateProfile } from "./CreateProfile"
export { default as Clinics } from "./Clinics"
export { default as IndividualClinic } from "./IndividualClinic"
export { default as Appointments } from "./Appointments"
export { default as PrivateUser } from "./routes/PrivateUser"